config/routes.rb
Rails.application.routes.draw do
  devise_for :makers
  devise_for :users

  resources :videos do
    collection do
      get 'my_videos', as: :my
      patch 'like'
    end
  end

  root 'videos#index'

  resources :comments, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :authorable,  polymorphic: true
  belongs_to :commentable, polymorphic: true

  validates_presence_of :content
end

app/models/maker.rb
class Maker < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable

  acts_as_voter

  validates_presence_of :first_name, :last_name, :nickname

  has_many :videos, dependent: :destroy
  has_many :comments, as: :authorable


  def name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable

  acts_as_voter

  has_many :comments, as: :authorable

  validates_presence_of :nickname


end

app/models/video.rb
class Video < ActiveRecord::Base
  paginates_per 15
  
  acts_as_votable

  belongs_to :maker

  has_many :comments, as: :commentable

  has_attached_file :video,
    styles: {
      # medium: { geometry: "640x480", format: 'flv' },
      thumb:  { geometry: "100x100#", format: 'jpg', time: 10 }
    },
    processors: [:transcoder]
  do_not_validate_attachment_file_type :video
  # validates_attachment_content_type :video,
  #     content_type: ["video/3gpp"]

  validates_presence_of :title, :video

  scope :by_user_id, -> user_id { where(user_id: user_id) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :signed_in?, :signed_in_model, :signed_in_id

  include ApplicationHelper



  protected

  def signed_in_model
    return 'Maker' if maker_signed_in?
    return 'User'  if user_signed_in?
    return nil
  end

  def signed_in_id
    return current_maker.id if maker_signed_in?
    return current_user.id  if user_signed_in?
    return nil
  end

  def signed_in?
    user_signed_in? || maker_signed_in?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:nickname, :first_name, :last_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:nickname, :first_name, :last_name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    if @comment.valid?
      redirect_to request.referrer, notice: 'You have added a new comment!'
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:content, :authorable_type, :authorable_id, :commentable_type, :commentable_id)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_maker!, except: [:index, :show, :like]
  before_action :set_video,           only:   [:edit, :show, :destroy, :update]
  before_action :check_access,        only:   [:edit, :destroy, :update]


  def index
    @videos = Video.order(created_at: :desc).page(params[:page])
  end

  def show
    if signed_in?
      @comments = @video.comments.where.not(id: nil)
      @comment  = @video.comments.build
    else
      flash.now[:alert] = 'You need to sign-in to comment or vote'
    end
  end

  def my_videos
    @videos = current_maker.videos.order(created_at: :desc).page(params[:page])
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.create(video_params)
    if @video.valid?
      redirect_to my_videos_path, notice: 'You have uploaded a new video!'
    else
      render :new
    end
  end

  def update
    if @video.update(video_params)
      redirect_to my_videos_path, notice: 'You have updated your video!'
    else
      render :edit
    end
  end

  def destroy
    @video.video.clear
    @video.destroy
    redirect_to my_videos_path, notice: 'You have deleted your video!'
  end

  def like
    @video = Video.find(params[:video_id])
    @voter = params[:voter_model].constantize.find(params[:voter_id])

    if @voter.voted_for? @video
      @video.unliked_by @voter
    else
      @video.liked_by @voter
    end

    @likes_count = @video.votes_for.size

    respond_to do |format|
      format.js
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :maker_id, :description, :video)
  end

  def check_access
    if Video.find(params[:id]).maker_id == current_maker.id
      true
    else
      redirect_to root_path
      flash[:alert] = 'Access denied!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield(:title).present? ? yield(:title) + ' | Makers' : 'Makers'

    = stylesheet_link_tag "application"

    %link{:href => "https://fonts.googleapis.com/css?family=Roboto&subset=latin,cyrillic", :rel => "stylesheet", :type => "text/css"}
    
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-static-top.navbar-inverse{:role => "navigation"}
      .container
        %ul.nav.navbar-nav
          = active_link_to "All videos", videos_path, wrap_tag: :li, active: /\/videos$/
        %ul.nav.navbar-nav{:style => "float: right"}
          - if maker_signed_in?
            = active_link_to "My videos", my_videos_path, wrap_tag: :li

          - if maker_signed_in? || user_signed_in?
            = active_link_to "Profile", maker_signed_in? ? edit_maker_registration_path : edit_user_registration_path, wrap_tag: :li

            = active_link_to "Log out", maker_signed_in? ? destroy_maker_session_path : destroy_user_session_path, method: :delete, wrap_tag: :li
          - if !maker_signed_in? && !user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Sign in as
                %b.caret
              %ul.dropdown-menu{:role => "menu"}
                = active_link_to "Maker", new_maker_session_path, wrap_tag: :li
                = active_link_to "User",  new_user_session_path,  wrap_tag: :li
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Sign up as
                %b.caret
              %ul.dropdown-menu{:role => "menu"}
                = active_link_to "Maker", new_maker_registration_path, wrap_tag: :li
                = active_link_to "User",  new_user_registration_path,  wrap_tag: :li

    .container
      .row
        .col-md-12
          = yield


  - if alert.present? || notice.present?
    - message = escape_javascript(alert || notice)
    - type    = alert ? 'danger' : 'info'
    :javascript
      $.notify({
        message: "#{message.html_safe}"
        },{
        offset: 30,
        type: "#{type}",
        placement: {
        from: "top",
        align: "center"
        },
        animate: {
        enter: 'animated zoomInDown',
        exit: 'animated zoomOutUp'
        }
      });

app/views/videos/_form.html.haml
= f.hidden_field :maker_id, value: current_maker.id

.form-group
  %label.col-md-2.control-label Title
  .col-md-10
    = f.text_field :title, :class => 'form-control', :placeholder => "Title"
.form-group
  %label.col-md-2.control-label Description
  .col-md-10
    = f.text_area :description, :class => 'form-control', :placeholder => "Description"
.form-group
  %label.col-md-2.control-label Video
  .col-md-10
    = f.file_field :video

app/views/videos/edit.html.haml
= title "Edit video"

.col-md-10
  = form_for [@video], :html => { class: 'form-horizontal', role: 'form', multipart: true } do |f|
    = render :partial => 'form', :locals => { f: f }
    .form-group
      .col-md-10.col-md-offset-2
        = submit_tag 'Update', :class => 'btn btn-primary'
        = link_to 'Delete', @video, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'

app/views/videos/index.html.haml
= title "All Videos"

%h2 All Videos
.row
  - @videos.each do |video|
    .col-sm-6.col-md-4.col.xs-1
      .thumbnail
        = videojs_rails sources: { video.video.content_type.split("/").last => video.video.url } , class: 'list' do
          Please enable
          %b JavaScript
          to see this content.
        .caption
          %p.author-of-video.pull-right
            by
            = video.maker.name
          %h3= video.title
          .row
            .col-xs-3.col-md-4.col-sm-6
              = link_to 'See details', video, class: 'btn btn-primary'

.pagination-wrapper
  = paginate @videos

app/views/videos/like.js.haml
$('#votes-count').text("#{@likes_count }");

app/views/videos/my_videos.html.haml
= title "My videos"

= link_to 'Upload video', new_video_path, class: 'btn btn-primary pull-right'
%h2 My videos
- if @videos.any?
  .row
    - @videos.each do |video|
      .col-sm-6.col-md-4.col.xs-1
        .thumbnail
          / = video_tag video.video.url, :controls => true
          = videojs_rails sources: { video.video.content_type.split("/").last => video.video.url } , class: 'list' do
            Please enable
            %b JavaScript
            to see this content.
          .caption
            %p.author-of-video.pull-right
              by
              = video.maker.name
            %h3= video.title
            .row
              .col-xs-3.col-md-4.col-sm-6
                = link_to 'See details', video, class: 'btn btn-primary'
              .col-xs-3.col-md-2.col-sm-4
                = link_to 'Edit', edit_video_path(video), class: 'btn btn-primary'

  .pagination-wrapper
    = paginate @videos
- else
  %p You have not uploaded any videos yet.

app/views/videos/new.html.haml
= title "New video"

.col-md-10
  = form_for [@video], :html => { class: 'form-horizontal', role: 'form', multipart: true } do |f|
    = render :partial => 'form', :locals => { f: f }
    .form-group
      .col-md-10.col-md-offset-2
        = submit_tag 'Create', :class => 'btn btn-primary'
        = link_to    'Cancel', my_videos_path, :class => 'btn btn-default'

app/views/videos/show.html.haml
= title "Video \"#{@video.title}\""

.col-md-7
  %h2= @video.title
  .embed-responsive.embed-responsive-4by3
    = videojs_rails sources: { @video.video.content_type.split("/").last => @video.video.url }, class: 'single' do
      Please enable
      %b JavaScript
      to see this content.

  - if signed_in?
    %p.likes.pull-left
      = fa_icon 'heart', class: 'heart-vote', data: { video_id: "#{@video.id}", voter_model: "#{signed_in_model}", voter_id: "#{signed_in_id}" }
      %span#votes-count
        = @video.votes_for.size

  %p.author-of-video.pull-right
    by
    = @video.maker.name
  .well= @video.description

  - if signed_in?
    %section#comments
      %h2 Comments
      - if @comments
        - @comments.each do |comment|
          .comment
            %p
              = comment.authorable.nickname
              \:
            .well= comment.content

      = form_for [@comment], html: {class: 'form-horizontal', role: 'form'} do |f|
        = f.hidden_field :authorable_type,  value: signed_in_model
        = f.hidden_field :authorable_id,    value: signed_in_id
        = f.hidden_field :commentable_type, value: @video.class.to_s
        = f.hidden_field :commentable_id,   value: @video.id
        = f.text_area :content, class: 'form-control'
        %br/
        = f.submit 'Comment', class: 'btn btn-primary'


    